### ISSUE TITLE
GSEA Error

### ISSUE THREAD

**Issue by HGmin1159** [EngreitzLab/gene_network_evaluation#62]
While running the GSEA, I keep encountering the following error. It works for some numbers of factors and libraries, but it fails about half the time:

```
Traceback (most recent call last):
File"/proj/hyejunglab/cropseq/Jiseok/analysis/SCZcropseq_paper_2/Supp_Analysis/Script/gene_program_evaluation/evaluation_pipeline.py", line 243, in <module>
    main(args.config)
File"/proj/hyejunglab/cropseq/Jiseok/analysis/SCZcropseq_paper_2/Supp_Analysis/Script/gene_program_evaluation/evaluation_pipeline.py", line 112, in main
    res = compute_geneset_enrichment(
File"/proj/hyejunglab/cropseq/Jiseok/analysis/SCZcropseq_paper_2/Supp_Analysis/Script/gene_program_evaluation/src/evaluation/enrichment_geneset.py", line 394, in compute_geneset_enrichment
    loadings = get_program_gene_loadings(
File"/proj/hyejunglab/cropseq/Jiseok/analysis/SCZcropseq_paper_2/Supp_Analysis/Script/gene_program_evaluation/src/evaluation/enrichment_geneset.py", line 66, in get_program_gene_loadings
    gene_names = get_idconversion(mdata[prog_key].uns['var_names'], organism=organism)
File"/proj/hyejunglab/cropseq/Jiseok/analysis/SCZcropseq_paper_2/Supp_Analysis/Script/gene_program_evaluation/src/evaluation/enrichment_geneset.py", line 35, in get_idconversion
    bm = Biomart()
  File "/nas/longleaf/home/mhg/.conda/envs/anaconda_env/lib/python3.8/site-packages/gseapy/biomart.py", line 76, in init
    self._marts = self.get_marts()["Mart"].to_list()
  File "/nas/longleaf/home/mhg/.conda/envs/anaconda_env/lib/python3.8/site-packages/gseapy/biomart.py", line 157, in get_marts
    marts = [e.attrib for e in ET.XML(resp.text)]
File"/nas/longleaf/home/mhg/.conda/envs/anaconda_env/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 62, column 2
Thu Dec  5 16:34:09 EST 2024
```

**Comment by aron0093** [comment]
Would you be able to send me a minimal example to reproduce the error? A mdata object subset from your full data that reproduces the error would help me in diagnosing the problem.
